# Generated by Django 2.2 on 2021-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='权限id')),
                ('module_name', models.CharField(default=None, max_length=32, null=True, verbose_name='权限模块名')),
                ('title', models.CharField(default=None, max_length=32, null=True, verbose_name='权限名')),
                ('urls', models.CharField(default=None, max_length=128, null=True, verbose_name='权限路径')),
                ('status', models.BooleanField(default=True, null=True, verbose_name='状态')),
                ('updated_time', models.DateTimeField(default=None, null=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'auth',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色id')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='角色名')),
                ('status', models.BooleanField(default=True, null=True, verbose_name='状态')),
                ('updated_time', models.DateTimeField(default=None, null=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RoleAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(default=None, null=True, verbose_name='角色id')),
                ('auth_id', models.IntegerField(default=None, null=True, verbose_name='权限id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'role_auths',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='用户名')),
                ('email', models.CharField(default=None, max_length=32, null=True, verbose_name='邮箱')),
                ('is_admin', models.BooleanField(default=False, null=True, verbose_name='是否是管理员')),
                ('status', models.BooleanField(default=True, null=True, verbose_name='状态')),
                ('updated_time', models.DateTimeField(default=None, null=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('user_id', models.IntegerField(default=None, null=True, verbose_name='用户id')),
                ('role_id', models.IntegerField(default=None, null=True, verbose_name='角色id')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
    ]
